apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-image:v1.2.3
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/my-app/config
      volumes:
      - name: config-volume
        configMap:
          name: my-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
