name: Dependent Pipeline

on:
  push:
    branches-ignore:
      - master

  workflow_run:
    workflows: ["Main Pipeline"]
    branches:
      - master
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: echo 123
