on:
  push:
    branches:
      - main
    commit:
      message: "Update image tag"

jobs:
  if_tag_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Execute the pipeline only for update tag commits
      run: |
        echo This pipeline is triggered because of the update tag commit.