on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

    - name: Create new tag
      run: |
        NEW_TAG="v$(date +%Y%m%d%H%M%S)"
        git tag $NEW_TAG
        git push --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}