on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    - name: Checkout code
      uses: actions/checkout@v3

    steps:
    - run: |
        echo The PR was MERGED

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update image tag in deployment.yaml and commit changes
      run: |
        NEW_TAG="${{ steps.tag_version.outputs.new_tag }}"

        ls -al
        
        FILE_PATH="k8s/base/dapr/deployment.yml"
        
        sed -i "s|image:my-app-image:[0-9]\+\.[0-9]\+\.[0-9]\+|image:my-app-image:$NEW_TAG|" $FILE_PATH
        
    - name: Auto commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update image tag to my-app-image:$NEW_TAG"
        file_pattern: "k8s/base/dapr/deployment.yml"
        github_token: ${{ secrets.GITHUB_TOKEN }}